# Generated by Django 4.1.3 on 2023-03-09 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_topic_room_hots_message_room_topic"),
    ]

    operations = [
        migrations.RenameField(
            model_name="room",
            old_name="hots",
            new_name="host",
        ),
    ]
