# Generated by Django 4.1.3 on 2023-03-11 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_rename_hots_room_host"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="room",
            options={"ordering": ["-updated", "-created"]},
        ),
    ]
